version: '3.8'

services:
  # Database Layer - Postgres SQL
  db:
    image: postgres:15
    container_name: tg_web_app_db
    env_file:
      - .env-non-dev
    ports:
      - "4321:5432"
      # - "${DB_PORT}:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  # Cache Layer - Redis
  redis:
    image: redis:7-alpine
    container_name: tg_web_app_redis
    # command: redis-server --appendonly yes
    ports:
      - "6378:6379"
      # - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  # Backend Layer - FastAPI
  backend_app:
    image: tg_web_app_backend
    container_name: tg_web_app_backend
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    command: sh -c "alembic upgrade head && gunicorn backend.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env-non-dev
    ports:
      - "9000:8000"
      # - "${BACKEND_PORT}:8000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  # Celery Layer - Celery
  celery:
    image: tg_web_app_celery
    container_name: tg_web_app_celery
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    command: sh -c "celery -A backend.celery_app.app:celery_app worker -l INFO"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env-non-dev
    networks:
      - app-network
    restart: unless-stopped


  # # Celery Beat
  # celery_beat:
  #   image: tg_web_app_celery
  #   container_name: tg_web_app_celery_beat
  #   build:
  #     context: . # celery это библиотека, у неё нет образа, берём из основного билда
  #   # Если не работает эта команда, используйте закомментированную
  #   # command: ["/booking/docker/celery.sh", "celery_beat"] # Второй аргумен для if/elif в скрипте
  #   command: sh -c "celery -A app.tasks.celery:celery worker -l INFO -B"
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   env_file:
  #     - .env-non-dev


  # Flower Layer - Flower
  flower:
    image: tg_web_app_flower
    container_name: tg_web_app_flower
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    command: sh -c "celery -A backend.celery_app.app:celery_app flower"
    # При запуске через nginx необходимо запускать команду ниже для корректной работы js и css
    # command: sh -c "celery --app=app.tasks.celery:celery flower --url_prefix=/flower"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env-non-dev
    ports:
      - "5555:5555"
      # - "${FLOWER_PORT}:5555"
    networks:
      - app-network
    restart: unless-stopped


  # Monitoring Storage - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - backend_app
      # backend_app:
      #   condition: service_healthy
    ports:
      - "9080:9090"
      # - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  # Monitoring Dashboard - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      prometheus:
        condition: service_healthy
    env_file:
      - .env-non-dev
    ports:
      - "3333:3000"
      # - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./backend/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./backend/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


# Volumes
volumes:
  postgresdata:
    driver: local
  redisdata:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local


# Networks
networks:
  app-network:
    driver: bridge
    name: tg_web_app_network
