"""add_telegram_fields_to_user_and_webapp_data

Revision ID: 037229c06548
Revises: 301ccfd0261c
Create Date: 2025-07-09 19:27:26.265356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "037229c06548"
down_revision: Union[str, Sequence[str], None] = "301ccfd0261c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_webapp_data", sa.Column("user_data", sa.JSON(), nullable=True)
    )
    op.add_column(
        "telegram_webapp_data", sa.Column("chat_data", sa.JSON(), nullable=True)
    )
    op.add_column(
        "telegram_webapp_data",
        sa.Column("start_param", sa.String(length=255), nullable=True),
    )
    op.add_column("users", sa.Column("photo_url", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("is_premium", sa.Boolean(), nullable=False))
    op.add_column(
        "users", sa.Column("telegram_username", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_username")
    op.drop_column("users", "is_premium")
    op.drop_column("users", "photo_url")
    op.drop_column("telegram_webapp_data", "start_param")
    op.drop_column("telegram_webapp_data", "chat_data")
    op.drop_column("telegram_webapp_data", "user_data")
    # ### end Alembic commands ###
