"""add all other tables: Achievement, UserAchievement, GameSettings, TelegramWebAppData

Revision ID: 27bb7a00467e
Revises: bcbd1e58349f
Create Date: 2025-06-21 20:40:12.290305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27bb7a00467e"
down_revision: Union[str, Sequence[str], None] = "bcbd1e58349f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=255), nullable=True),
        sa.Column("condition_type", sa.String(length=50), nullable=False),
        sa.Column("condition_value", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_achievements_id"), "achievements", ["id"], unique=False)
    op.create_table(
        "game_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.String(length=50), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("theme", sa.String(length=20), nullable=True),
        sa.Column("sound_enabled", sa.Boolean(), nullable=True),
        sa.Column("vibration_enabled", sa.Boolean(), nullable=True),
        sa.Column("controls", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_settings_id"), "game_settings", ["id"], unique=False)
    op.create_table(
        "telegram_webapp_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("init_data", sa.Text(), nullable=False),
        sa.Column("query_id", sa.String(length=255), nullable=True),
        sa.Column("auth_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hash", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telegram_webapp_data_id"), "telegram_webapp_data", ["id"], unique=False
    )
    op.create_table(
        "user_achievements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.Column(
            "earned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("is_new", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_achievements_id"), "user_achievements", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_achievements_id"), table_name="user_achievements")
    op.drop_table("user_achievements")
    op.drop_index(op.f("ix_telegram_webapp_data_id"), table_name="telegram_webapp_data")
    op.drop_table("telegram_webapp_data")
    op.drop_index(op.f("ix_game_settings_id"), table_name="game_settings")
    op.drop_table("game_settings")
    op.drop_index(op.f("ix_achievements_id"), table_name="achievements")
    op.drop_table("achievements")
    # ### end Alembic commands ###
