"""change COlumn onto mapped_column

Revision ID: 76b38160557d
Revises: 27bb7a00467e
Create Date: 2025-06-21 22:48:33.430330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "76b38160557d"
down_revision: Union[str, Sequence[str], None] = "27bb7a00467e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "achievements", "points", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "game_sessions", "score", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "game_sessions", "duration", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "game_sessions", "level", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "game_sessions",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "game_sessions", "is_completed", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "game_settings",
        "difficulty",
        existing_type=sa.VARCHAR(length=20),
        nullable=False,
    )
    op.alter_column(
        "game_settings", "theme", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "game_settings", "sound_enabled", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "game_settings", "vibration_enabled", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user_achievements",
        "earned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user_achievements", "is_new", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("users", "is_bot", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "max_score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("users", "max_score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_bot", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "user_achievements", "is_new", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user_achievements",
        "earned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "game_settings", "vibration_enabled", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "game_settings", "sound_enabled", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "game_settings", "theme", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "game_settings",
        "difficulty",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.alter_column(
        "game_sessions", "is_completed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "game_sessions",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column("game_sessions", "level", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "game_sessions", "duration", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("game_sessions", "score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("achievements", "points", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
