"""add nulable for is_premium

Revision ID: 898b4f1cf2d0
Revises: 037229c06548
Create Date: 2025-07-09 19:32:14.604005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "898b4f1cf2d0"
down_revision: Union[str, Sequence[str], None] = "037229c06548"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_premium", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_premium", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
