"""Add refresh_token

Revision ID: e0c34cacc0bc
Revises: 898b4f1cf2d0
Create Date: 2025-08-03 01:19:55.567222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0c34cacc0bc'
down_revision: Union[str, Sequence[str], None] = '898b4f1cf2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_webapp_data', 'user_data')
    op.drop_column('telegram_webapp_data', 'start_param')
    op.drop_column('telegram_webapp_data', 'chat_data')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'is_premium')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('telegram_webapp_data', sa.Column('chat_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('telegram_webapp_data', sa.Column('start_param', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('telegram_webapp_data', sa.Column('user_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
