"""rm useless tabels

Revision ID: e8bb634e6431
Revises: 89d6113c9421
Create Date: 2025-08-09 14:16:36.904793

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e8bb634e6431'
down_revision: Union[str, Sequence[str], None] = '89d6113c9421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем ненужные таблицы
    op.drop_table('user_achievements')
    op.drop_table('achievements')
    op.drop_table('game_settings')
    op.drop_table('telegram_webapp_data')
    op.drop_table('refresh_tokens')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Восстанавливаем удаленные таблицы (если нужно)
    # Это сложная операция, так как нужно воссоздать структуру таблиц
    # В реальном проекте лучше создать отдельную миграцию для восстановления

    # ### end Alembic commands ###
